# Generated by Django 4.2.5 on 2023-09-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_customer_post_alter_customuser_managers_and_more'),
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(default='news/default.png', null=True, upload_to='news/')),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='employee',
            field=models.ManyToManyField(related_name='halls', to='authorization.employee'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.employee'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='museum.hall'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('numOfPpl', models.PositiveIntegerField()),
                ('code', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.employee')),
            ],
        ),
    ]
