# Generated by Django 4.2.5 on 2023-09-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_customer_post_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='news/default.png', null=True, upload_to='employee/'),
        ),
    ]
